# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Python_source\心语\心语UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 618)
        Form.setMinimumSize(QtCore.QSize(1000, 618))
        Form.setMaximumSize(QtCore.QSize(1000, 618))
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:/桌面美化/ICO/爱心.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-image:url(D:/A_图/beijing.jpg);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 71))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    background:transparent;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("F:/桌面美化/ICO/爱心.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 54, 19))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    font-size : 15pt;\n"
"    background:transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(190, 40, 261, 151))
        self.pushButton.setStyleSheet("QPushButton \n"
"{\n"
"    \n"
"    background-color:rgb(255,255,255); \n"
"    color:rgb(6,168,255); \n"
"    border:2px solid rgb(6,168,255); \n"
"    font-size:14px; \n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(212,243,255); \n"
"    color:rgb(6,168,255);\n"
"    border:2px solid rgb(6,168,255); \n"
"    border-radius:14px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(175,232,255); \n"
"    color:white; \n"
"    border:2px solid rgb(6,168,255); \n"
"    border-radius:14px;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 50, 50, 50))
        self.pushButton_2.setStyleSheet("/*按钮静止无操作样式*/\n"
"QPushButton\n"
"{\n"
"    background-image:rgb(255,255,255); \n"
"    border-radius:25px;\n"
"    border:2px solid rgb(6,168,255);\n"
"   \n"
"  \n"
"}\n"
"\n"
"/*鼠标悬停在按钮*/\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(212,243,255);\n"
"    color:rgb(6,168,255);\n"
"    border:2px solid rgb(6,168,255);\n"
"    border-radius:25px;\n"
"}\n"
"\n"
"/*鼠标按下按钮*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(175,232,255);\n"
"    color:white;\n"
"    border:2px solid rgb(6,168,255);\n"
"    border-radius:25px;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("F:/桌面美化/ICO/favicon (2).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("/*按钮静止无操作样式*/\n"
"QPushButton \n"
"{\n"
"    background:transparent;\n"
"}\n"
"\n"
"/*鼠标悬停在按钮*/\n"
"QPushButton:hover\n"
"{\n"
"    background:transparent;\n"
"    text-decoration:underline;\n"
"}\n"
"\n"
"/*鼠标按下按钮*/\n"
"QPushButton:pressed\n"
"{\n"
"#测试;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(260, 80, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    background:transparent;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(200, 110, 241, 75))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(270, 320, 281, 61))
        self.label_4.setStyleSheet("QLabel{\n"
"\n"
"border-radius:12px\n"
"\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "心语"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aaffff;\">〇〇3</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "这个年纪"))
        self.label_3.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bahnschrift Condensed\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:600; color:#00ff7f;\">12-4 23：47：06</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文隶书\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:24px; background-color:#ffffff;\"><span style=\" font-family:\'arial,宋体,sans-serif\'; font-size:14px; color:#333333; background-color:#ffffff;\">慈母用手中的针线，为远行的儿子赶制身上的衣衫。临行前一针针密密地缝缀，怕的是儿子回来得晚衣服破损。有谁敢说，子女像小草那样微弱的孝心，能够报答得了像春晖普泽的慈母恩情呢？</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "TextLabel"))
